<?php

return [
    'No' => 'No',
    'first_name' => 'First Name',
    'last_name' => 'Last Name',
    'email' => 'Email',
    'phone' => 'Phone',
    'position' => 'Position',
    'salary' => 'Salary',
    'salary_from' => 'Salary From',
    'salary_to' => 'Salary To',
    'created_at' => 'Created At',
    'updated_at' => 'Updated At',
    'name' => 'Name',
    'report_summary' => 'Report Summary',
    'total_employees' => 'Total Employees',
    'total_salaries' => 'Total Salaries',
    'date' => 'Date',
    'generated_by' => 'Generated by Filament Employee Management System',
];
