<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Employees Report</title>
    <style>
        body { font-family: sans-serif; font-size: 14px; }
        .header { width: 100%; border-bottom: 2px solid #ddd; margin-bottom: 20px; padding-bottom: 10px; }
        .logo { float: left; }
        .invoice-details { float: right; text-align: right; }
        .clearfix::after { content: ""; clear: both; display: table; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #eee; padding: 8px; text-align: left; }
        th { background-color: #f8f9fa; font-weight: bold; }
        .text-right { text-align: right; }
        .total-section { margin-top: 20px; text-align: right; }
        .footer { position: fixed; bottom: 0; left: 0; right: 0; font-size: 12px; text-align: center; color: #888; }
    </style>
</head>
<body>
    <div class="header clearfix">
        <div class="logo">
             <h1>iFundev</h1>
        </div>
        <div class="invoice-details">
            <h2>Employee Report</h2>
            <p><strong>Date:</strong> {{ now()->format('Y-m-d') }}</p>
        </div>
    </div>

    <div>
        <strong>Report Summary</strong><br>
        Total Employees: {{ $employees->count() }}
    </div>

    <table>
        <thead>
            <tr>
                <th>First Name</th>
                <th>Last Name</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Position</th>
                <th class="text-right">Salary</th>
            </tr>
        </thead>
        <tbody>
            @foreach($employees as $employee)
                <tr>
                    <td>{{ $employee->first_name }}</td>
                    <td>{{ $employee->last_name }}</td>
                    <td>{{ $employee->email }}</td>
                    <td>{{ $employee->phone }}</td>
                    <td>{{ $employee->position }}</td>
                    <td class="text-right">${{ number_format($employee->salary, 2) }}</td>
                </tr>
            @endforeach
        </tbody>
        <tfoot>
            <tr>
                <td colspan="5" class="text-right"><strong>Total Salaries:</strong></td>
                <td class="text-right"><strong>${{ number_format($employees->sum('salary'), 2) }}</strong></td>
            </tr>
        </tfoot>
    </table>

    <div class="footer">
        Generated by Filament Employee Management System
    </div>
</body>
</html>
